# -*- coding: utf-8 -*-
"""LMS1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ybNTS0kwFQ4f3OFoEKxlp0UWeT6d4DX
"""

!apt update
!apt install -y chromium-browser chromium-chromedriver

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--window-size=1920,1080")
chrome_options.binary_location = "/usr/bin/chromium-browser"

driver = webdriver.Chrome(options=chrome_options)

# ------------------------------- #
# ✅ INSTALL REQUIRED PACKAGES (COLAB)
# ------------------------------- #
!apt update
!apt install -y chromium-browser chromium-chromedriver
!pip install selenium pandas

# ------------------------------- #
# ✅ IMPORTS
# ------------------------------- #
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
import time
import os
import re
import zipfile
import pandas as pd
import shutil

# ------------------------------- #
# 🔐 YOUR CREDENTIALS
# ------------------------------- #
USERNAME = "test@.com"
PASSWORD = "test123"

# ------------------------------- #
# 🚀 SETUP DRIVER (FIXED)
# ------------------------------- #
chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--window-size=1920,1080")
chrome_options.binary_location = "/usr/bin/chromium-browser"

# Download folder
download_dir = "/content/flying_journey_downloads"

if os.path.exists(download_dir):
    shutil.rmtree(download_dir)
os.makedirs(download_dir)

prefs = {
    "download.default_directory": download_dir,
    "download.prompt_for_download": False,
    "download.directory_upgrade": True
}
chrome_options.add_experimental_option("prefs", prefs)

# ✅ FIXED DRIVER INIT (NO Service PATH)
driver = webdriver.Chrome(options=chrome_options)

wait = WebDriverWait(driver, 45)

# ------------------------------- #
# 🌐 OPEN WEBSITE
# ------------------------------- #
url = "https://lms.upgradabroad.com/reports/flying-journey"
driver.get(url)

# ------------------------------- #
# 🔑 LOGIN
# ------------------------------- #
try:
    email = wait.until(EC.presence_of_element_located((By.ID, "email")))
    password = driver.find_element(By.ID, "password")

    email.send_keys(USERNAME)
    password.send_keys(PASSWORD)

    driver.find_element(By.XPATH, "//button[contains(text(),'Sign In')]").click()
    print("✅ Login submitted")

    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))
except Exception as e:
    print("❌ Login issue:", e)

# ------------------------------- #
# 📌 NAVIGATE TAB
# ------------------------------- #
try:
    tab = wait.until(EC.element_to_be_clickable(
        (By.XPATH, "//*[contains(text(),'Flying Journey')]")
    ))
    tab.click()
    print("✅ Tab clicked")

    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))
except Exception as e:
    print("❌ Tab issue:", e)

# ------------------------------- #
# ------------------------------- #
# ↗↗ APPLY FILTERS
# ------------------------------- #

# Country = ALL
try:
    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))

    country = wait.until(EC.presence_of_element_located(
        (By.XPATH, "//label[contains(text(),'Select Country')]/following::select[1]")
    ))

    wait.until(EC.presence_of_element_located(
        (By.XPATH, "//label[contains(text(),'Select Country')]/following::select[1]/option[text()='ALL']")
    ))

    Select(country).select_by_visible_text("ALL")
    print("✅ Country filter set to ALL")

    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))

except Exception as e:
    print(f"❌ Country filter skipped: {e}")


# First Apply Filter
try:
    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))

    apply_filters_btn = wait.until(EC.element_to_be_clickable(
        (By.XPATH, "//*[contains(text(),'Apply Filter(s)')]")
    ))

    driver.execute_script("arguments[0].click();", apply_filters_btn)

    print("✅ Apply Filter(s) clicked (1st time)")

    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))

except Exception as e:
    print(f"❌ First Apply Filter issue: {e}")


# ------------------------------- #
# ------------------------------- #
# 🧹 CLEAR FLYING STATUS (FINAL FINAL FIX)
# ------------------------------- #
try:
    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))
    print("⏳ Clearing Flying Status...")

    while True:
        remove_buttons = driver.find_elements(
            By.XPATH,
            "//ul[@id='select2-flying_status-container']//button[contains(@class,'select2-selection__choice__remove')]"
        )

        if not remove_buttons:
            break

        # Click first available remove button
        driver.execute_script("arguments[0].click();", remove_buttons[0])
        time.sleep(0.5)

    print("✅ Flying Status cleared successfully")

except Exception as e:
    print(f"❌ Flying Status clear failed: {e}")

# Second Apply Filter
try:
    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))

    apply_filters_btn = wait.until(EC.element_to_be_clickable(
        (By.XPATH, "//*[contains(text(),'Apply Filter(s)')]")
    ))

    driver.execute_script("arguments[0].click();", apply_filters_btn)

    print("✅ Apply Filter(s) clicked (2nd time)")

    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))
    time.sleep(5)

except Exception as e:
    print(f"❌ Second Apply Filter issue: {e}")

# Apply again
try:
    driver.find_element(By.XPATH, "//*[contains(text(),'Apply Filter(s)')]").click()
    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))
    time.sleep(5)
except:
    pass

# ------------------------------- #
# 🔍 SEARCH
# ------------------------------- #
try:
    driver.find_element(By.XPATH, "//button[contains(text(),'Search')]").click()
    print("✅ Search clicked")
    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))
    time.sleep(5)
except Exception as e:
    print("❌ Search error:", e)

# ------------------------------- #
# ------------------------------- #
# ↓↓ CLICK EXPORT (FIXED)
# ------------------------------- #
try:
    print("⏳ Preparing to click Export...")

    # ✅ VERY IMPORTANT — wait for page to fully settle after search
    wait.until(EC.invisibility_of_element_located((By.ID, "loadingScreen")))
    time.sleep(3)

    # ✅ Use better XPath (based on class instead of href)
    export_btn = wait.until(EC.presence_of_element_located(
        (By.XPATH, "//a[contains(@class,'ajax-download-request') and contains(.,'Export')]")
    ))

    # Scroll into view
    driver.execute_script("arguments[0].scrollIntoView({block:'center'});", export_btn)
    time.sleep(2)

    # ✅ Force click using JS (most important fix)
    driver.execute_script("arguments[0].click();", export_btn)

    print("✅ Export clicked successfully")

    # ✅ Wait for confirmation toast (more flexible match)
    wait.until(EC.presence_of_element_located(
        (By.XPATH, "//*[contains(text(),'successfully accepted')]")
    ))

    print("✅ Download confirmation message received!")

except Exception as e:
    print(f"❌ Export failed:", e)

# ------------------------------- #
# 📂 DOWNLOAD HISTORY
# ------------------------------- #
try:
    driver.find_element(By.XPATH, "//*[contains(text(),'Download History')]").click()
    print("✅ Opened Download History")
except Exception as e:
    print("❌ Download history error:", e)

# ------------------------------- #
# ⏳ WAIT FOR PROCESS
# ------------------------------- #
print("⏳ Waiting for processing...")

report_id = None
processed = False

for i in range(60):
    try:
        links = driver.find_elements(By.XPATH, "//a[contains(@href,'download/')]")

        max_id = -1
        for link in links:
            href = link.get_attribute("href")
            match = re.search(r'/download/(\\d+)', href)
            if match:
                max_id = max(max_id, int(match.group(1)))

        if max_id != -1:
            report_id = str(max_id)

            row = driver.find_element(By.XPATH, f"//tr[.//a[contains(@href,'{report_id}')]]")
            if "Processed" in row.text:
                print(f"✅ Report {report_id} ready")
                processed = True
                break

    except:
        pass

    driver.find_element(By.XPATH, "//button[contains(text(),'Search')]").click()
    time.sleep(10)

# ------------------------------- #
# 📦 DOWNLOAD + UNZIP
# ------------------------------- #
if processed:
    link = driver.find_element(By.XPATH, f"//a[contains(@href,'{report_id}')]")
    link.click()
    print("⬇️ Download started")

    time.sleep(10)

    zip_files = [f for f in os.listdir(download_dir) if f.endswith(".zip")]

    if zip_files:
        zip_path = os.path.join(download_dir, zip_files[0])
        extract_dir = os.path.join(download_dir, "extracted")

        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_dir)

        print(f"✅ File unzipped to: {extract_dir}")

        csv_files = [f for f in os.listdir(extract_dir) if f.endswith(".csv")]

        if csv_files:
            df = pd.read_csv(os.path.join(extract_dir, csv_files[0]))
            print(df.head())
        else:
            print("❌ No CSV found")
else:
    print("❌ Report not ready")

# ------------------------------- #
# 🏁 CLOSE
# ------------------------------- #
driver.quit()

